#### 使用mycat
spring:
  datasource:
    dynamic:
      primary: master
      strict: false
      datasource:
        master:
          #url: jdbc:p6spy:mysql://localhost:8066/mybatis_p
          url: jdbc:p6spy:mysql://192.168.2.102:3306/ccsx_data
          username: root
          password: sonoscape
          driver-class-name: com.p6spy.engine.spy.P6SpyDriver
mybatis-plus:
  type-enums-package: com.chen.mybatisplus.entity.enums
  mapper-locations: classpath:/mappers/*.xml
logging:
  level:
    com.chen: debug