server:
  port: 8080
spring:
  application:
    name: mybatisplus
  datasource:
    #    url: jdbc:mysql:///mybatis_p
    url: jdbc:p6spy:mysql:///mybatis_p
    username: root
    password: root
    driver-class-name: com.p6spy.engine.spy.P6SpyDriver
mybatis-plus:
  type-enums-package: com.chen.mybatisplus.entity.enums
logging:
  level:
    com.chen: debug